### ISSUE TITLE
Normalize trailing /

### ISSUE THREAD

**Issue by satazor** [npm/hosted-git-info#14]
I've found that several modules on npm have a trailing / in the repository URL, e.g.: https://github.com/CollinEstes/astro-cli/blob/261cdecade954f9b4277ccf968b577513edda587/package.json#L16

These trailing slashes are ok while cloning https:// from GitHub URLs.  I don't know if that's a problem on GitLab or Bitbucket. Also I haven't tested having trailing slashes in ssh and other protocols.

The issue here is that `.fromUrl()` returns null for these URLs. Thoughts?

**Comment by iarna** [comment]
`fromUrl()` returning null just means that it gets treated as a generic git source, without the option of any site-specific optimizations. Still supporting that would be nice.
