### ISSUE TITLE
Do not throw on malformed URI

### ISSUE THREAD

**Issue by satazor** [npm/hosted-git-info#15]
If a malformed URI  (e.g.: git://github.com/balderdashy/waterline-%s.git) is passed to `hosted-git-info` it will throw with `URIError: URI malformed`.

Ideally, these exceptions will be caught and `null` should be returned.
Thoughts?

**Comment by satazor** [comment]
I've found another case that throws, but this type with a `cannot read property map of undefined`

```js
require("hosted-git-info").fromUrl('git://github.com')
```

The issue is in this line: https://github.com/npm/hosted-git-info/blob/master/index.js#L50

**Comment by iarna** [comment]
ty, these are both great catches
