### ISSUE TITLE
Keep the casing of the owner name in the normalized GitHub repo URL

### ISSUE THREAD

**Issue by zkochan** [npm/hosted-git-info#16]
I created the issue in normalize-package-data but then realized that the core of the problem is in hosted-git-info
https://github.com/npm/normalize-package-data/issues/73

Here is an example of the issue
https://tonicdev.com/56fc202b81168d1100ac3b5d/57001f25a2d934120019b7f7

**Comment by iarna** [comment]
While the hosted git providers seem to handle case changes just fine, I agree that mucking with case doesn't seem like something we should be doing.
