### ISSUE TITLE
parse gitlab url have BUG

### ISSUE THREAD

**Issue by maxming2333** [npm/hosted-git-info#23]
Test git url : `git@gitlab.demo-ice.com:page/fe-demo.git`

Eg:

```js
var hostedGitInfo = require("hosted-git-info")
var info = hostedGitInfo.fromUrl("git@gitlab.demo-ice.com:page/fe-demo.git");
console.log(info); // ==> undefined
```

**Comment by iarna** [comment]
This is correct. This only parses gitlab URLs hosted by `gitlab.com`. That's the "hosted" in "hosted-git-info". There's no way for us to distinguish a self-hosted gitlab (or github enterprise instance) from any other git server as there's no difference in the url format.
