### ISSUE TITLE
2.6.0 contains breaking changes that breaks things down stream

### ISSUE THREAD

**Issue by watson** [npm/hosted-git-info#31]
v2.6.0 adds a requirement for Node.js v4 or newer, so should have been published as v3.0.0 to signal the breaking change.

I know that no one should be running 0.12 or 0.10 any more, but the fact is that a lot of people are still maintaining legacy systems 😢 And while I wish that we could all just forget about pre v4 versions of Node, I still think it should be considered a breaking change when changing the required version of Node.js.

In my case this breaks the [dependency-check](https://github.com/maxogden/dependency-check) module when run on Node.js 0.12 or older, which in turn breaks a lot of CI tests that happen to still test on old Node.js versions.

I think 2.6.0 should just be removed from npm (or a 2.6.1 that reverts the commits should be published) and a 3.0.0 should be published as a replacement

**Comment by mischah** [comment]
Hej @zkat,

will you fix that?

Cheers, Michael

**Comment by iarna** [comment]
Reverted and landed in 2.6.1.
