### ISSUE TITLE
[Question] why v2.6.1 and v2.6.0 diverged?

### ISSUE THREAD

**Issue by huochunpeng** [npm/hosted-git-info#33]
Is it to fix regression?

I am confused where I should create my PR (on master or latest). I am trying to create a PR to update Github tarball url to latest `https://codeload.github.com`.

**Comment by iarna** [comment]
Because the tag for 2.6.0 wasn't pushed and the source repo was misplaced so we couldn't push it. The only thing lost was the version tagging, the source was all merged.
