### ISSUE TITLE
Add support for more providers…

### ISSUE THREAD

**Issue by iarna** [npm/hosted-git-info#4]
Possibilities include:

assembla
gitorious
codeplex
sourceforge

**Comment by neocotic** [comment]
Assembla appears to only support Subversion, Gitorious was shutdown and merged into GitLab shortly have this issue was raised, and CodePlex is [in the process of being shutdown](https://blogs.msdn.microsoft.com/bharry/2017/03/31/shutting-down-codeplex/).

SourceForge seems to be the only one on this list that's still worth considering, however, I wonder if the website is really still relevant? Shouldn't be too difficult to support though if the decision was made to.

**Comment by neocotic** [comment]
I've just taken a quick look at SourceForge and it's not really going to fit in well, in my opinion. URLs for raw files are download-only, so cannot be used to link to raw file served in plain text. Also, I see no way of generating a tarball URL as they appear to generate ad-hoc snapshot downloads.

I managed to work around some of the other issues, I think, but it's not pretty:

``` javascript
sourceforge: {
  'protocols': [ 'git', 'http', 'git+ssh', 'git+https', 'ssh', 'https' ], // Confirm: Need to verify all options
  'domain': 'git.code.sf.net',
  'pathmatch': /^[/]p[/](?:([^/]+)[/])?([^/]+)[/]code(?:[.]git)?$/,
  'filetemplate': 'https://sourceforge.net/p/{project}/code/ci/{committish}/tree/{path}?format=raw', // Confirm: URL is for download only
  'bugstemplate': 'https://sourceforge.net/p/{project}/tickets/',
  'gittemplate': 'git://{auth@}{domain}/p/{project}/code.git{#committish}',
  'sshtemplate': 'git@{domain}:p/{project}/code.git{#committish}',
  'sshurltemplate': 'git+ssh://git@{domain}/p/{project}/code.git{#committish}',
  'browsetemplate': 'https://sourceforge.net/p/{project}/code/ci/{committish}/tree/',
  'docstemplate': 'https://sourceforge.net/p/{project}/code/ci/{committish}/tree/#readme',
  'httpstemplate': 'git+https://{domain}/p/{project}/code.git{#committish}',
  'shortcuttemplate': '{type}:{project}{#committish}',
  'pathtemplate': '{project}{#committish}', // Confirm: Should this be "p/{project}/code{#committish}"?
  'tarballtemplate': '' // Confirm: Appears to be unavailable
}
```

My suggestion would be to forget about SourceForge.

**Comment by Ardrete** [comment]
I think this don't work with github enterprise

**Comment by isaacs** [comment]
We can reopen if another host becomes popular in the space.  For now, I think we've got the main ones covered.
