### ISSUE TITLE
TypeError: this[method] is not a function

### ISSUE THREAD

**Issue by ybbjegj** [npm/hosted-git-info#49]
hi, 
When I used it today, I found the following error

TypeError: this[method] is not a function
at GitHost.toString (node_modules/hosted-git-info/git-host.js:154:22)

**Comment by czy88840616** [comment]
I have the same problem.

**Comment by teazean** [comment]
I have the same problem, too.

**Comment by ycjcl868** [comment]
+ 1

**Comment by wangzhezhezhe** [comment]
+1

**Comment by isaacs** [comment]
Fixed by 3b1d629, published on v2.8.2.
