### ISSUE TITLE
Issue with `gittemplate`

### ISSUE THREAD

**Issue by whitneyit** [npm/hosted-git-info#5]
Hi there!

I am having a problem using npm to install a module with the `git+https://` protocol. I have traced the issue back to this repo and specifically [line 107 on index.js](https://github.com/npm/hosted-git-info/blob/f7c0be8b815d4f56897596dd114f6fb664c180b3/index.js#L107).

The issue that I am facing is caused because of port `22` being blocked. To get around the port being blocked I have chosen to use the `git+https://` protocol.

Unfortunately, the logic in [index.js](https://github.com/npm/hosted-git-info/blob/f7c0be8b815d4f56897596dd114f6fb664c180b3/index.js#L107) is converting that protocol back to `git://`. To remedy this I had to downgrade npm to `v1.4.6` which did not have this problem.

I propose a PR that would dynamically generate the `gittemplate` and set the protocol to `https://` if the original protocol was `git+https://`.

I am happy to work on this PR should the solution be fitting.

**Comment by othiym23** [comment]
1. You should be fine with `npm@2.5.1`, which doesn't use `hosted-git-info`.
2. See npm/npm#7867, which I'm going to close this in favor of. We've been gradually working towards getting this right, but it's taken us a few passes to get everything completely nailed down. 

Thanks for the thorough analysis and writing up the issue!

**Comment by whitneyit** [comment]
Ok thanks for this heads up. Cheers.

Regards,
James
