### ISSUE TITLE
Pathmatch for GitLab treats tarball archives as git repos

### ISSUE THREAD

**Issue by isaacs** [npm/hosted-git-info#50]
Better path match (discovered during pair debugging: `/^[/]([^/]+)[/](?!.*\/-\/)(.+?)(?:[.]git|[/])?$/`)

**Comment by mikemimik** [comment]
start here from this branch:
https://github.com/npm/hosted-git-info/compare/legacy-ayfkm

**Comment by isaacs** [comment]
Fixed by #51 and #52
