### ISSUE TITLE
[BUG] Failed to parse git url 

### ISSUE THREAD

**Issue by link89** [npm/hosted-git-info#60]
Hi, I think the new version just breaks the git URL parser.
https://github.com/npm/hosted-git-info/blob/6f39e93bae9162663af6f15a9d10bce675dd5de3/index.js#L112

Now it failed to handle dependency like this:
`git+ssh://git@git.unlucky.com:RND/electron-tools/some-tool#2.0.1`

Can you release a hotfix for this? It breaks a lot of things and hard to work around in projects. 

node version: 12.0.0 

@isaacs 
@darcyclarke

**Comment by isaacs** [comment]
Confirmed, we'll take a look at this today.
