### ISSUE TITLE
[BUG] "url.URL is not a constructor" error on Node 6 < v6.13.0

### ISSUE THREAD

**Issue by billneff79** [npm/hosted-git-info#61]
# What / Why
The unit tests (and actual usage in the wild) fail with the error:
` "url.URL is not a constructor" `

## When
I run the unit tests or use the package on Node v6 (which seems to be supported?) with a version less than v6.13.0, where the URL constructor was first introduced to Node v6.

## Where
All places

### Current Behavior
* Run unit tests on Node v6 < v6.13.0 (e.g. v6.12.3) and notice the error

### Steps to Reproduce
* Run unit tests on Node v6 < v6.13.0 (e.g. v6.12.3) and notice the error

### Expected Behavior
* Running unit tests on all versions of Node v6 passes without error

## Who
* @stevenhilder 

## References
Introduced in PR #58 
https://github.com/npm/hosted-git-info/pull/58/files#diff-168726dbe96b3ce427e7fedce31bb0bcR112

**Comment by darcyclarke** [comment]
This was fixed in https://github.com/npm/hosted-git-info/pull/66 & is landed as [`hosted-git-info@2.8.8`](https://www.npmjs.com/package/hosted-git-info?activeTab=versions). We'll try to roll out a cli update as soon as possible which will include this dep update (likely as `npm@6.14.2`)
