### ISSUE TITLE
How can I use self host url?

### ISSUE THREAD

**Issue by fulong** [npm/hosted-git-info#67]

**Comment by fulong** [comment]
![image](https://user-images.githubusercontent.com/1610395/94415051-a12e4200-01af-11eb-93ef-b071141b2a99.png)
gitHosts array is unchangeably

**Comment by lukekarrys** [comment]
See the test case for `localhost` urls, which provides a good example on how to use custom hosts: https://github.com/npm/hosted-git-info/blob/70a770d1202128e15887d69dfd5c930e4ff29a00/test/localhost.js
