### ISSUE TITLE
[QUESTION] Can you please add changelogs for v4?

### ISSUE THREAD

**Issue by gr2m** [npm/hosted-git-info#82]
# What / Why

As you published v4 to npm, the bots are out there sending their pull requests, such as https://github.com/semantic-release/semantic-release/pull/1838. It would be very helpful to know what exactly changed with the upgrade, but I cannot find any notes 

## Where

* n/a

## Who

* n/a

## References

* n/a

**Comment by raineorshine** [comment]
Hard to find, but:

> rewrite the entire module (#80)

> * feat! rewrite the world

> all internals have been rewritten to maintain a similar contract but to remove
> excessive use of regular expressions, unnecessary loops, the custom string
> templating engine, and various other bits of complexity

> BREAKING CHANGE extending with custom providers has changed
