### ISSUE TITLE
NPM vulnerability database update

### ISSUE THREAD

**Issue by nothingismagick** [npm/hosted-git-info#85]
@bscofield @isaacs

Can you please mark the 2.8.9 release as actually fixing the vuln too?
https://www.npmjs.com/advisories/1677

This is started to trickle upstream:
https://github.com/npm/normalize-package-data/issues/120

Here is the proof, in case anyone needs it:
https://github.com/npm/hosted-git-info/compare/v2.8.8...v2.8.9

**Comment by RealDrewKlayman** [comment]
@nothingismagick They just did.

**Comment by nothingismagick** [comment]
I'll check locally and then close.

**Comment by nothingismagick** [comment]
Thanks, can confirm audit passes.
