### ISSUE TITLE
It should bump a major version when the protocol is changed from `https:` to `git+https:`

### ISSUE THREAD

**Issue by stevemao** [npm/hosted-git-info#9]
https://github.com/npm/normalize-package-data/pull/63

Because this is not backward compatible and it breaks my test 

https://travis-ci.org/stevemao/get-pkg-repo/jobs/57572081#L90
https://travis-ci.org/stevemao/get-pkg-repo/jobs/62977512#L90

**Comment by iarna** [comment]
Did you link to the correct travis pages there? The first one shows tests passing and the second one shows them failing for reasons that … [don't appear to be related](https://travis-ci.org/stevemao/get-pkg-repo/jobs/62977512#L166-L176)

For reference, the change you're referencing is here:
https://github.com/npm/hosted-git-info/commit/3bca5a500f612c9304b335e1f63fde794fca2695

To my mind, just because a change breaks a test suite does not imply a breaking change, as it can _easily_ be a test suite that's too specific and testing things that are not actually a part of the published API. When I made this change (and bumped the version) I did not view the specific URLs you get back to be a part of the API– it promises you a URL, but does not promise anything about the URL. (This could be better documented.)

**Comment by stevemao** [comment]
The links are correct. Let me elaborate the problem in my module

I use https://github.com/stevemao/get-pkg-repo/blob/master/index.js#L45 to normalize my pkgData. It used to return `https:` as the protocol but now it returns `git+https:`. I use the protocol https://github.com/stevemao/get-pkg-repo/blob/master/index.js#L15 to check to see if it's `https:`. If not simply convert it to `http:`. Hence the tests fail. The logic is quite similar to what `npm.repo` does except you guys are not using `normalize-package-data` there.

Well this is probably not the best example but point is the output is completely different (from `https:` to `git+https:`).

> it promises you a URL, but does not promise anything about the URL.
Say I had module. In version v1.0.0 the output is `true` but in v1.1.0 the output becomes `false` for a very good reason. I promise you a `Boolean` but not the actual value. However whoever depends on me would get a completely opposite value. In a lot of modules the public API never changed but they bump a major version because the output might be unexpected. To my mind this is quite a change and certainly not backward compatible (for whoever relies on the protocol) unless you say we shouldn't rely on the output of the protocol because it's changing.

**Comment by iarna** [comment]
Reading through your code, it looks like you're using code copied from:

https://github.com/npm/npm/blob/v2.10.1/lib/repo.js

But that's designed to work with with `normalize-package-data@1`, not `@2`. By contrast, this is the version that's supposed to work with `@2`:

https://github.com/npm/npm/blob/b1c7e5d/lib/repo.js

That the former ever worked was luck.

So what I'm going to do is update the documentation to `hosted-git-info` and `normalize-package-data` to be clearer on what is and isn't a part of the API contract.

**Comment by stevemao** [comment]
:+1:

**Comment by SamB** [comment]
Okay, what you've written seems reasonable:

> I do not consider the specific format of the urls returned from, say `.https()` to be a part of the contract. The contract is that it will return a string that can be used to fetch the repo via HTTPS. But what that string looks like, specifically, can change.

Unfortunately, `git+https://` doesn't actually seem to fulfill that contract:

https://repl.it/@SamB1/FullAgreeableSystemsoftware

```js
// @ts-check

const child_process = require('child_process');
const hostedGitInfo = require('hosted-git-info');

const info = hostedGitInfo.fromUrl('hosted-git-info/npm');

child_process.execSync(`git ls-remote ${info.https()}`);
```

Ends up outputting:

```
 fatal: Unable to find remote helper for 'git+https'
Error: Command failed: git ls-remote git+https://github.com/hosted-git-info/npm.git
fatal: Unable to find remote helper for 'git+https'

    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:653:13)
    at evalmachine.<anonymous>:8:15
    at Script.runInContext (vm.js:107:20)
    at Object.runInContext (vm.js:285:6)
    at evaluate (/run_dir/repl.js:133:14)
    at ReadStream.<anonymous> (/run_dir/repl.js:116:5)
    at ReadStream.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
```
